name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: 
    branches: 
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Generate Dark Mode Metrics
      - name: Generate Metrics (Dark Mode)
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: AndrewMommers
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Melbourne
          filename: metrics-dark.svg
          
          # Features
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          plugin_calendar: yes
          plugin_calendar_limit: 1
          
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          
          plugin_gists: yes
          
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          plugin_projects: yes
          plugin_projects_limit: 4
          
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          
          plugin_repositories: yes
          plugin_repositories_featured: AndrewMommers/mommersco-platform
          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          
          plugin_traffic: yes
          
          # Styling for Dark Mode
          config_display: large
          config_animations: yes
          config_base_indepth: yes
          config_padding: 10%
          
          # Dark Mode Custom Styling
          extras_css: |
            * {
              --color-calendar-graph-day-bg: #0b1221 !important;
              --color-calendar-graph-day-border: transparent !important;
              --color-calendar-graph-day-L1-bg: #1e3a5f !important;
              --color-calendar-graph-day-L2-bg: #2d5aa0 !important;
              --color-calendar-graph-day-L3-bg: #3b7dd8 !important;
              --color-calendar-graph-day-L4-bg: #00e5ff !important;
              --color-text-primary: #e6f2ff !important;
              --color-text-secondary: #7c3aed !important;
              --color-text-tertiary: #39ff14 !important;
            }
            
            .field {
              background: linear-gradient(135deg, #0b1221 0%, #1e3a5f 100%) !important;
              border: 2px solid #00e5ff !important;
              border-radius: 15px !important;
              box-shadow: 0 0 20px #00e5ff30 !important;
            }
            
            .field:hover {
              animation: glow 2s ease-in-out infinite alternate !important;
            }
            
            @keyframes glow {
              from { box-shadow: 0 0 20px #00e5ff30; }
              to { box-shadow: 0 0 30px #00e5ff60, 0 0 40px #39ff1430; }
            }
            
            h2 {
              color: #00e5ff !important;
              text-shadow: 0 0 10px #00e5ff, 0 0 20px #00e5ff, 0 0 30px #00e5ff !important;
              font-weight: bold !important;
            }
            
            .progress-bar {
              background: linear-gradient(90deg, #7c3aed 0%, #00e5ff 50%, #39ff14 100%) !important;
              border-radius: 10px !important;
              box-shadow: 0 0 10px #00e5ff50 !important;
            }
            
            .languages .field .chartist-ct-chart .ct-series circle {
              stroke: #00e5ff !important;
              stroke-width: 3px !important;
            }
            
            .calendar .day {
              stroke: #00e5ff !important;
              stroke-width: 1px !important;
            }
            
            .calendar .day[data-level="1"] { fill: #1e3a5f !important; }
            .calendar .day[data-level="2"] { fill: #2d5aa0 !important; }
            .calendar .day[data-level="3"] { fill: #3b7dd8 !important; }
            .calendar .day[data-level="4"] { fill: #00e5ff !important; }
            
            .chart-bars .entry .value {
              color: #e6f2ff !important;
            }
            
            .activity {
              background: #0b1221 !important;
              border: 1px solid #7c3aed !important;
              border-radius: 8px !important;
            }
            
            .stargazers path {
              stroke: #00e5ff !important;
              fill: #00e5ff20 !important;
            }

      # Generate Light Mode Metrics
      - name: Generate Metrics (Light Mode)
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: AndrewMommers
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Melbourne
          filename: metrics-light.svg
          
          # Features
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          plugin_calendar: yes
          plugin_calendar_limit: 1
          
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          
          plugin_gists: yes
          
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          plugin_projects: yes
          plugin_projects_limit: 4
          
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          
          plugin_repositories: yes
          plugin_repositories_featured: AndrewMommers/mommersco-platform
          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          
          plugin_traffic: yes
          
          # Styling for Light Mode
          config_display: large
          config_animations: yes
          config_base_indepth: yes
          config_padding: 10%
          
          # Light Mode Custom Styling
          extras_css: |
            * {
              --color-calendar-graph-day-bg: #ebedf0 !important;
              --color-calendar-graph-day-border: #ffffff !important;
              --color-calendar-graph-day-L1-bg: #c6e48b !important;
              --color-calendar-graph-day-L2-bg: #7bc96f !important;
              --color-calendar-graph-day-L3-bg: #239a3b !important;
              --color-calendar-graph-day-L4-bg: #196127 !important;
              --color-text-primary: #24292f !important;
              --color-text-secondary: #656d76 !important;
              --color-text-tertiary: #0969da !important;
            }
            
            .field {
              background: linear-gradient(135deg, #ffffff 0%, #f6f8fa 100%) !important;
              border: 2px solid #0969da !important;
              border-radius: 15px !important;
              box-shadow: 0 4px 12px rgba(9, 105, 218, 0.15) !important;
            }
            
            .field:hover {
              box-shadow: 0 8px 25px rgba(9, 105, 218, 0.25) !important;
              transform: translateY(-2px) !important;
              transition: all 0.3s ease !important;
            }
            
            h2 {
              color: #0969da !important;
              font-weight: bold !important;
              text-shadow: none !important;
            }
            
            .progress-bar {
              background: linear-gradient(90deg, #7c3aed 0%, #0969da 50%, #1a7f37 100%) !important;
              border-radius: 10px !important;
              box-shadow: 0 2px 8px rgba(9, 105, 218, 0.2) !important;
            }
            
            .languages .field .chartist-ct-chart .ct-series circle {
              stroke: #0969da !important;
              stroke-width: 2px !important;
            }
            
            .calendar .day {
              stroke: #d0d7de !important;
              stroke-width: 1px !important;
            }
            
            .calendar .day[data-level="0"] { fill: #ebedf0 !important; }
            .calendar .day[data-level="1"] { fill: #c6e48b !important; }
            .calendar .day[data-level="2"] { fill: #7bc96f !important; }
            .calendar .day[data-level="3"] { fill: #239a3b !important; }
            .calendar .day[data-level="4"] { fill: #196127 !important; }
            
            .chart-bars .entry .value {
              color: #24292f !important;
            }
            
            .activity {
              background: #f6f8fa !important;
              border: 1px solid #d0d7de !important;
              border-radius: 8px !important;
            }
            
            .stargazers path {
              stroke: #0969da !important;
              fill: rgba(9, 105, 218, 0.1) !important;
            }
            
            /* Text readability improvements */
            text {
              fill: #24292f !important;
            }
            
            .metric {
              color: #24292f !important;
            }

      # Generate Default Version (Dark for backwards compatibility)
      - name: Generate Metrics (Default)
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: AndrewMommers
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Melbourne
          filename: metrics.svg
          
          # Features (same as dark mode)
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          plugin_calendar: yes
          plugin_calendar_limit: 1
          
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          
          plugin_gists: yes
          
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          plugin_projects: yes
          plugin_projects_limit: 4
          
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          
          plugin_repositories: yes
          plugin_repositories_featured: AndrewMommers/mommersco-platform
          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          
          plugin_traffic: yes
          
          # Default Styling (Dark Mode)
          config_display: large
          config_animations: yes
          config_base_indepth: yes
          config_padding: 10%
          
          # Default Custom Styling (same as dark)
          extras_css: |
            * {
              --color-calendar-graph-day-bg: #0b1221 !important;
              --color-calendar-graph-day-border: transparent !important;
              --color-calendar-graph-day-L1-bg: #1e3a5f !important;
              --color-calendar-graph-day-L2-bg: #2d5aa0 !important;
              --color-calendar-graph-day-L3-bg: #3b7dd8 !important;
              --color-calendar-graph-day-L4-bg: #00e5ff !important;
              --color-text-primary: #e6f2ff !important;
              --color-text-secondary: #7c3aed !important;
              --color-text-tertiary: #39ff14 !important;
            }
            
            .field {
              background: linear-gradient(135deg, #0b1221 0%, #1e3a5f 100%) !important;
              border: 2px solid #00e5ff !important;
              border-radius: 15px !important;
              box-shadow: 0 0 20px #00e5ff30 !important;
            }
            
            h2 {
              color: #00e5ff !important;
              text-shadow: 0 0 10px #00e5ff40 !important;
              font-weight: bold !important;
            }
            
            .progress-bar {
              background: linear-gradient(90deg, #7c3aed 0%, #00e5ff 50%, #39ff14 100%) !important;
              border-radius: 10px !important;
              box-shadow: 0 0 10px #00e5ff50 !important;
            }