name: Profile 3D Contributions
on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          username: AndrewMommers
          output: profile-3d-contrib
          # Theme with brand hues (pick one to keep; animated looks great)
          # Available: profile-green-animate / profile-night-green / profile-season-animate / etc.
          # Files created in ./profile-3d-contrib/
      - name: Commit 3D assets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib/*.svg
          git commit -m "Update 3D contributions" || echo "No changes"
          git push
